INSERT INTO EMPLOYEE(ID,NAME,ADDRESS,EMAIL)VALUES(001,'STEVE THOMAS','LINT DRIVE','ST@GMAIL.COM');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS,EMAIL)VALUES(002,'VALRY WAYDE','THE GROVE','VL@GMAIL.COM');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS,EMAIL)VALUES(003,'ANDREW TEAL','WEST ONE','AN@GMAIL.COM');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS,EMAIL)VALUES(004,'ZULHRA WHITE','DAGENHAM','ZL@GMAIL.COM');

--CREATE TABLE  IF NOT EXISTS USERS(
--						ID INT(11) NOT NULL AUTO_INCREMENT,
--						MESSAGE VARCHAR(255),
--						NAME VARCHAR(255),
--						CURRENT_TIME VARCHAR(255)
--						PRIMARY KEY (id))
--						ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
--				
--				
--		
--    
--
--INSERT INTO USERS (ID, MESSAGE,NAME,CURRENT_TIME) VALUES(001,'about to make a post','conroy white','23-12-2020');
--
--INSERT INTO POSTS (ID, DISCRIPTION,USERS_ID) VALUES(001,'FIRST POST',001);
--INSERT INTO POSTS (ID, DISCRIPTION,USERS_ID) VALUES(002,'FIRST POST',001);
--INSERT INTO POSTS (ID, DISCRIPTION,USERS_ID) VALUES(003,'FIRST POST',001);


